update

diff --git a/config/functions b/config/functions
--- a/config/functions
+++ b/config/functions
@@ -129,6 +129,21 @@ build_msg() {
   fi
 }
 
+# prints a warning if the file slated for removal doesn't exist
+# this allows us to continue instead of bailing out with just "rm"
+safe_remove() {
+  local path="$1"
+
+  [ -z "${path}" ] && return 0
+
+  if [ -f "${path}" -o -d "${path}" ]; then
+    rm -r "${path}"
+  elif [ -n "${PKG_NAME}" ]; then
+    print_color CLR_WARNING "safe_remove: path does not exist: [${PKG_NAME}]: ${path}\n"
+  else
+    print_color CLR_WARNING "safe_remove: path does not exist: ${path}\n"
+  fi
+}
 
 ### BUILDSYSTEM HELPERS ###
 # check if a flag is enabled
@@ -342,11 +357,9 @@ setup_toolchain() {
 create_meson_conf() {
   local endian root properties
   case "$1" in
-    target|init)    endian="little"
-                    root="$SYSROOT_PREFIX/usr"
+    target|init)    root="$SYSROOT_PREFIX/usr"
                     ;;
-    host|bootstrap) endian="big"
-                    root="$TOOLCHAIN"
+    host|bootstrap) root="$TOOLCHAIN"
                     ;;
   esac
 
@@ -365,12 +378,14 @@ llvm-config = '$SYSROOT_PREFIX/usr/bin/llvm-config-host'
 system = 'linux'
 cpu_family = '$TARGET_ARCH'
 cpu = '$TARGET_SUBARCH'
-endian = '$endian'
+endian = 'little'
 
 [properties]
 root = '$root'
 $(python -c "import os; print('c_args = {}'.format([x for x in os.getenv('CFLAGS').split()]))")
 $(python -c "import os; print('c_link_args = {}'.format([x for x in os.getenv('LDFLAGS').split()]))")
+$(python -c "import os; print('cpp_args = {}'.format([x for x in os.getenv('CXXFLAGS').split()]))")
+$(python -c "import os; print('cpp_link_args = {}'.format([x for x in os.getenv('LDFLAGS').split()]))")
 ${!properties}
 EOF
 }
@@ -488,7 +503,7 @@ debug_strip() {
 }
 
 init_package_cache() {
-  local _ANCHOR="@?+?@" DIR
+  local _ANCHOR="@?+?@"
   local temp_global temp_local
 
   # If the package caches are unset, then populate them
@@ -496,22 +511,16 @@ init_package_cache() {
     temp_global="$(mktemp)"
     temp_local="$(mktemp)"
 
-    # cache project/device folder for a package
-    if [ -n $DEVICE ]; then
-      for DIR in $(find $ROOT/projects/$PROJECT/devices/$DEVICE/packages -type d 2>/dev/null); do
-        [ -r "$DIR/package.mk" ] && echo "${DIR}${_ANCHOR}" >> "${temp_local}"
-      done
+    # cache project/device folder for packages
+    if [ -n "${DEVICE}" ]; then
+      find "${ROOT}/projects/${PROJECT}/devices/${DEVICE}/packages" -type f -name package.mk 2>/dev/null | sed "s#/package\.mk\$#${_ANCHOR}#" >> "${temp_local}"
     fi
 
-    # cache project folder for a package
-    for DIR in $(find $ROOT/projects/$PROJECT/packages -type d 2>/dev/null); do
-      [ -r "$DIR/package.mk" ] && echo "${DIR}${_ANCHOR}" >> "${temp_local}"
-    done
+    # cache project folder for packages
+    find "${ROOT}/projects/${PROJECT}/packages" -type f -name package.mk 2>/dev/null | sed "s#/package\.mk\$#${_ANCHOR}#" >> "${temp_local}"
 
     # cache packages folder
-    for DIR in $(find $ROOT/$PACKAGES -type d 2>/dev/null); do
-      [ -r "$DIR/package.mk" ] && echo "${DIR}${_ANCHOR}" >> "${temp_global}"
-    done
+    find "${ROOT}/${PACKAGES}" -type f -name package.mk 2>/dev/null | sed "s#/package\.mk\$#${_ANCHOR}#" >> "${temp_global}"
 
     _CACHE_PACKAGE_LOCAL="${BUILD}/.cache_package_local"
     _CACHE_PACKAGE_GLOBAL="${BUILD}/.cache_package_global"
@@ -614,14 +623,14 @@ check_device() {
 
 check_arch() {
   local dashes="===========================" arch_err_msg linux_config_dir
-  if [ -d ${PROJECT_DIR}/${PROJECT}/devices/${DEVICE}/linux ]; then
+  if [ -d "${PROJECT_DIR}/${PROJECT}/devices/${DEVICE}/linux" ]; then
     linux_config_dir="${PROJECT_DIR}/${PROJECT}/devices/$DEVICE/linux"
   else
     linux_config_dir="${PROJECT_DIR}/${PROJECT}/linux"
   fi
 
-  if [ ! -e $linux_config_dir/linux.${TARGET_PATCH_ARCH:-$TARGET_ARCH}.conf ] &&
-     ! ls $linux_config_dir/*/linux.${TARGET_PATCH_ARCH:-$TARGET_ARCH}.conf &>/dev/null; then
+  if [ ! -e "$linux_config_dir/linux.${TARGET_PATCH_ARCH:-$TARGET_ARCH}.conf" ] &&
+       ! ls "$linux_config_dir/"*/linux.${TARGET_PATCH_ARCH:-$TARGET_ARCH}.conf &>/dev/null; then
     arch_err_msg="\n $dashes$dashes$dashes"
     arch_err_msg="${arch_err_msg}\n ERROR: Architecture not found, use a valid Architecture"
     arch_err_msg="${arch_err_msg}\n for your project or create a new config"
@@ -705,7 +714,7 @@ get_pkg_variable() {
 
 # get package's build dir
 get_build_dir() {
-  local _PKG_NAME="$(get_pkg_variable "$1" PKG_NAME)" _PKG_VERSION="$(get_pkg_version "$1")"
+  local _PKG_NAME="${1%:*}" _PKG_VERSION="$(get_pkg_version "$1")"
   if [ -n "$_PKG_NAME" -a -n "$_PKG_VERSION" ]; then
     echo $BUILD/${_PKG_NAME}-${_PKG_VERSION}
   fi
@@ -751,11 +760,16 @@ get_pkg_directory() {
 }
 
 calculate_stamp() {
-  local stamp
+  local stamp data
+
   stamp="$PKG_DIR $PROJECT_DIR/$PROJECT/patches/$PKG_NAME"
   [ -n "$DEVICE" ] && stamp+=" $PROJECT_DIR/$PROJECT/devices/$DEVICE/patches/$PKG_NAME"
   [ -n "$PKG_NEED_UNPACK" ] && stamp+=" $PKG_NEED_UNPACK"
-  find ${stamp} -exec sha256sum {} \; 2>/dev/null | sed "s/ ${ROOT//\//\\/}\// /" | sort | sha256sum | cut -d" " -f1
+
+  data="$(find ${stamp} -exec sha256sum {} \; 2>/dev/null | sed "s/ ${ROOT//\//\\/}\// /")"
+  [ -n "${PKG_STAMP}" ] && data+=$'\n'"$(echo "${PKG_STAMP}" | sha256sum)"
+
+  echo "${data}" | sort | sha256sum | cut -d" " -f1
 }
 
 target_has_feature() {
@@ -869,7 +883,7 @@ source_package() {
   unset_functions
 
   if [ -n "${1}" ]; then
-    PKG_DIR="$(get_pkg_directory ${1})"
+    [ -f "${1}" ] && PKG_DIR="$(dirname "${1}")" || PKG_DIR="$(get_pkg_directory "${1}")"
 
     [ -n "$PKG_DIR" -a -r $PKG_DIR/package.mk ] || die "FAILURE: unable to source package - ${1}/package.mk does not exist"
 
@@ -883,6 +897,12 @@ source_package() {
     if [ "$PKG_IS_ADDON" = "yes" -o "$PKG_IS_ADDON" = "embedded" ] ; then
       [ -z $PKG_SECTION ] && PKG_ADDON_ID="$PKG_NAME" || PKG_ADDON_ID="${PKG_SECTION//\//.}.$PKG_NAME"
       [ "$PKG_ADDON_IS_STANDALONE" != "yes" ] && PKG_NEED_UNPACK="${PKG_NEED_UNPACK} $(get_pkg_directory $MEDIACENTER)"
+    fi
+
+    if [ -n "${PKG_DEPENDS_UNPACK}" ]; then
+      for _p in ${PKG_DEPENDS_UNPACK}; do
+        PKG_NEED_UNPACK+=" $(get_pkg_directory ${_p})"
+      done
     fi
 
     # Automatically set PKG_SOURCE_NAME unless it is already defined.
@@ -969,8 +989,10 @@ kernel_config_path() {
              $pkg_linux_dir/config/$config_name \
              ; do
     [[ $cfg =~ /devices//linux/ ]] && continue
-    [ -f "$cfg" ] && echo "$cfg" && break
+    [ -f "$cfg" ] && echo "$cfg" && return
   done
+
+  die "ERROR: Unable to locate kernel config for ${LINUX} - looking for ${config_name}"
 }
 
 kernel_make() {
@@ -1135,6 +1157,8 @@ done
 }
 
 install_addon_files() {
+  mkdir -p "$1"
+
   install_addon_source "$1"
   install_addon_images "$1"
   create_addon_xml "$1"
@@ -1173,7 +1197,7 @@ add_user() {
 
   mkdir -p ${INSTALL}/usr/cache
   touch ${INSTALL}/usr/cache/shadow
-  ln -sf /storage/.cache/shadow ${INSTALL}/etc/shadow
+  ln -sf /storage/.cache/shadow ${INSTALL}/etc/shadow 2>/dev/null || true
 
   PASSWORD="$2"
   if [ "$PASSWORD" = "x" ]; then
@@ -1194,7 +1218,7 @@ add_group() {
 }
 
 # Usage: enable_service <unit> [target]
-enable_service () {
+enable_service() {
   local unit="$1"
   local unit_dir="/usr/lib/systemd/system"
   local target="$2"
@@ -1214,6 +1238,179 @@ enable_service () {
       ln -sf ${unit} ${target_dir}/$unit_dir/${target}
     fi
   done
+}
+
+
+### MULTI-THREADED FUNCTION HELPERS ###
+# Test MTWITHLOCKS so that these functions are a no-op during non-multithreaded builds.
+
+# Prevent concurrent modifications to a package (unpack) or
+# package:target (install/build).
+#
+# If a package is already locked and the owner is ourselves
+# then assume we already have the required lock.
+pkg_lock() {
+  [ "${MTWITHLOCKS}" != "yes" ] && return 0
+
+  local pkg="$1" task="$2" parent_pkg="$3"
+  local this_job="${MTJOBID}"
+  local lock_job lock_seq lock_task lock_pkg locked=no
+  local fail_seq
+
+  exec 98>"${THREAD_CONTROL}/locks/${pkg}.${task}"
+  while [ : ]; do
+    read -r lock_job lock_seq lock_task lock_pkg <<<$(cat "${THREAD_CONTROL}/locks/${pkg}.${task}.owner" 2>/dev/null)
+    [ -n "${lock_job}" ] && break
+    flock --wait 1 --exclusive 98 && locked=yes && break
+  done
+
+  if [ "${locked}" = "no" -a "${lock_job}/${lock_seq}" != "${this_job}/${PARALLEL_SEQ}" ]; then
+    pkg_lock_status "STALLED" "${parent_pkg}" "${task}" "$(printf "waiting on [%02d] %s %s" ${lock_job} "${lock_task}" "${lock_pkg}")"
+    flock --exclusive 98
+  fi
+
+  # As we now have the lock, if .failed still exists then a previous process must have failed
+  if [ -f "${THREAD_CONTROL}/locks/${pkg}.${task}.failed" ]; then
+    fail_seq="$(< "${THREAD_CONTROL}/locks/${pkg}.${task}.failed")"
+    print_color CLR_ERROR "FAILURE: ${pkg}.${task}.failed exists, a previous dependency process has failed (seq: ${fail_seq})\n"
+    if [ -d "${THREAD_CONTROL}/logs" ]; then
+cat <<EOF
+
+The following logs for this failure are available:
+  stdout: ${THREAD_CONTROL}/logs/${fail_seq}/stdout
+  stderr: ${THREAD_CONTROL}/logs/${fail_seq}/stderr
+
+EOF
+    fi
+    return 1
+  fi
+
+  pkg_lock_status "LOCKED" "${pkg}" "${task}"
+}
+
+# Log additional information for a locked package.
+pkg_lock_status() {
+  [ "${MTWITHLOCKS}" != "yes" ] && return 0
+
+  local status="$1" pkg="$2" task="$3" msg="$4"
+  local this_job="${MTJOBID}" line
+
+  (
+    flock --exclusive 94
+
+    printf -v line "%s: <%06d> [%02d/%0*d] %-7s %-7s %-35s" \
+    "$(date +%Y-%m-%d\ %H:%M:%S.%N)" $$ ${this_job} ${#MTMAXJOBS} ${PARALLEL_SEQ:-0} "${status}" "${task}" "${pkg}"
+    [ -n "${msg}" ] && line+=" (${msg})"
+
+    echo "${line}" >>"${THREAD_CONTROL}/history"
+
+    if [ "${DASHBOARD}" != "no" ]; then
+      update_dashboard "${status}" "${pkg}" "${task}" "${msg}"
+    fi
+  ) 94>"${THREAD_CONTROL}/locks/.history"
+
+  if [ "${status}" = "LOCKED" ]; then
+    echo "${PARALLEL_SEQ}" > "${THREAD_CONTROL}/locks/${pkg}.${task}.failed"
+    echo "${this_job} ${PARALLEL_SEQ} ${task} ${pkg}" >"${THREAD_CONTROL}/locks/${pkg}.${task}.owner"
+  elif [ "${status}" = "UNLOCK" ]; then
+    rm "${THREAD_CONTROL}/locks/${pkg}.${task}.owner"
+    rm "${THREAD_CONTROL}/locks/${pkg}.${task}.failed"
+  fi
+
+  return 0
+}
+
+update_dashboard() {
+  [ "${MTWITHLOCKS}" != "yes" ] && return 0
+
+  local status="$1" pkg="$2" task="$3" msg="$4"
+  local line sedline preamble num elapsed projdevarch
+  local boldred boldgreen boldyellow endcolor
+
+  sedline=$((MTJOBID + 2))
+
+  num=$(< "${THREAD_CONTROL}/status.max")
+  if [ ${num} -lt ${sedline} ]; then
+    echo ${sedline} >"${THREAD_CONTROL}/status.max"
+    for i in $(seq $((num + 1)) ${sedline}); do echo "" >>"${THREAD_CONTROL}/status"; done
+  fi
+
+  num=$(< "${THREAD_CONTROL}/progress.prev")
+  projdevarch="${PROJECT}/"
+  [ -n "${DEVICE}" ] && projdevarch+="${DEVICE}/"
+  projdevarch+="${TARGET_ARCH}"
+  [ -n "${BUILD_SUFFIX}" ] && projdevarch+=", ${BUILD_SUFFIX}"
+  TZ=UTC0 printf -v elapsed "%(%H:%M:%S)T" $(($(date +%s) - MTBUILDSTART))
+  printf -v preamble "%s Dashboard (%s) - %d of %d jobs completed, %s elapsed" "${DISTRONAME}" "${projdevarch}" $((num + 1)) ${MTMAXJOBS} "${elapsed}"
+  printf -v preamble "%b%-105s %s" "\e[2J\e[0;0H" "${preamble//\//\\/}" "$(date "+%Y-%m-%d %H:%M:%S")"
+
+  if [ "${DISABLE_COLORS}" != "yes" ]; then
+    boldred="\e[1;31m"
+    boldgreen="\e[1;32m"
+    boldyellow="\e[1;33m"
+    white="\e[0;37m"
+    endcolor="\e[0m"
+
+    case "${status}" in
+      IDLE)    color="${white}";;
+      STALLED) color="${boldyellow}";;
+      MUTEX/W) color="${boldyellow}";;
+      FAILED ) color="${boldred}";;
+      *)       color="${boldgreen}";;
+    esac
+  fi
+
+  printf -v line "[%02d\/%0*d] %b%-7s%b %-7s %-35s" ${MTJOBID} ${#MTMAXJOBS} ${PARALLEL_SEQ:-0} "${color}" "${status//\//\\/}" "${endcolor}" "${task}" "${pkg}"
+  [ -n "${msg}" ] && line+=" ${msg//\//\\/}"
+
+  sed -e "1s/.*/${preamble}/;${sedline}s/.*/${line}/" -i "${THREAD_CONTROL}/status"
+}
+
+# Thread concurrency helpers to avoid concurrency issues with some code,
+# eg. when Python installs directly into $TOOLCHAIN.
+acquire_exclusive_lock() {
+  [ "${MTWITHLOCKS}" != "yes" ] && return 0
+
+  local pkg="$1" task="$2" lockfile="${3:-global}"
+  local this_job="${MTJOBID}"
+  local lock_job lock_seq lock_task lock_pkg locked=no
+
+  exec 96>"${THREAD_CONTROL}/locks/.mutex.${lockfile}"
+  while [ : ]; do
+    read -r lock_job lock_seq lock_task lock_pkg <<<$(cat "${THREAD_CONTROL}/locks/.mutex.${lockfile}.owner" 2>/dev/null)
+    [ -n "${lock_job}" ] && break
+    flock --wait 1 --exclusive 96 && locked=yes && break
+  done
+
+  if [ "${locked}" = "no" -a "${lock_job}/${lock_seq}" != "${this_job}/${PARALLEL_SEQ}" ]; then
+    pkg_lock_status "MUTEX/W" "${pkg}" "${task}" "$(printf "mutex: %s; waiting on [%02d] %s %s" "${lockfile}" ${lock_job} "${lock_task}" "${lock_pkg}")"
+    flock --exclusive 96
+  fi
+
+  pkg_lock_status "MUTEX" "${pkg}" "${task}" "mutex: ${lockfile}"
+
+  echo "${this_job} ${PARALLEL_SEQ} ${task} ${pkg}" >"${THREAD_CONTROL}/locks/.mutex.${lockfile}.owner"
+}
+
+release_exclusive_lock() {
+  [ "${MTWITHLOCKS}" != "yes" ] && return 0
+
+  local pkg="$1" task="$2" lockfile="${3:-global}"
+
+  pkg_lock_status "ACTIVE" "${pkg}" "${task}"
+
+  rm "${THREAD_CONTROL}/locks/.mutex.${lockfile}.owner"
+  flock --unlock 96 2>/dev/null
+}
+
+# Execute single command using mutex
+exec_thread_safe() {
+  local result
+  acquire_exclusive_lock "${PKG_NAME:exec}" "execcmd"
+  $@
+  result=$?
+  release_exclusive_lock "${PKG_NAME:exec}" "execcmd"
+  return ${result}
 }
 
 # Use distribution functions if any
