update1

diff --git a/config/options b/config/options
--- a/config/options
+++ b/config/options
@@ -28,19 +28,22 @@ TARGET_ARCH="${ARCH}"
 # read DISTRO version information
 . "${DISTRO_DIR}/${DISTRO}/version" || die "\nERROR: No distro version present\n"
 
+# read DISTRO version information
+. "${DISTRO_DIR}/${DISTRO}/version" || die "\nERROR: No distro version present\n"
+
 # read DISTRO options if available
 if [ -f "${DISTRO_DIR}/${DISTRO}/options" ]; then
-  . "${PROJECT_DIR}/${PROJECT}/options"
+  . "${DISTRO_DIR}/${DISTRO}/options"
 fi
 
 # read DISTRO custom options if available
 if [ -f "${DISTRO_DIR}/${DISTRO}/options_custom" ]; then
-  . "${PROJECT_DIR}/${PROJECT}/options_custom"
+  . "${DISTRO_DIR}/${DISTRO}/options_custom"
 fi
 
 # read PROJECT options if available
-if [ -f "${PROJECT_DIR}/${PROJECT}/devices/${DEVICE}/options" ]; then
-  . "${PROJECT_DIR}/${PROJECT}/devices/${DEVICE}/options"
+if [ -f "${PROJECT_DIR}/${PROJECT}/options" ]; then
+  . "${PROJECT_DIR}/${PROJECT}/options"
 fi
 
 # read DEVICE options if available
