init

diff --git a/scripts/create_addon b/scripts/create_addon
--- a/scripts/create_addon
+++ b/scripts/create_addon
@@ -79,20 +79,20 @@ function find_addons() {
       `# make entries unique` \
       | sort -u \
       `# select packages with PKG_IS_ADDON=yes (slow, but is a short list, now)` \
-      | xargs -n1 -I{} $SHELL -c '. ./config/options {} &>/dev/null; [ "$PKG_IS_ADDON" == "yes" ] && echo $PKG_NAME'
+      | xargs -n1 -I{} /bin/bash -c '. ./config/options {} &>/dev/null; [ "$PKG_IS_ADDON" = "yes" ] && echo $PKG_NAME'
   )
 
   # check if anything is found
   local _count=$(wc -w <<< $_addons)
-  if [ "$_count" == 0 ]; then
-    # handle embedded addons here. Should only build, when they explicte in the addon list
+  if [ $_count -eq 0 ]; then
+    # handle embedded addons here. Should only build when they are explictly specified in the addon list
     ( . ./config/options "$1" &>/dev/null
-      [ "$PKG_IS_ADDON" != "embedded" ] && exit 1
+      [ "$PKG_IS_ADDON" != "embedded" -a "$PKG_IS_ADDON" != "yes" ] && exit 1
       echo $PKG_NAME
     )
 
     # abort when nothing found and not embedded
-    if [ $? != 0 ]; then
+    if [ $? -ne 0 ]; then
       printf  "$(print_color CLR_ERROR "ERROR: '$1' matches nothing...")\n" ' '>&$SILENT_OUT
       printf  "for more informations type: ./scripts/create_addon --help\n" ' '>&$SILENT_OUT
       exit 1
@@ -159,17 +159,19 @@ pack_addon() {
         sha256sum $ADDON_JENKINS_ADDON_NAME.zip > $ADDON_JENKINS_ADDON_NAME.zip.sha256
       )
       printf  "%${BUILD_INDENT}c $(print_color CLR_INFO "*** creating $ADDON_JENKINS_ADDON_NAME.zip for Jenkins complete ***")\n" ' '>&$SILENT_OUT
+    else
+      printf  "%${BUILD_INDENT}c $(print_color CLR_INFO "*** creating $PKG_ADDON_ID complete ***")\n" ' '>&$SILENT_OUT
     fi
   fi
 }
 
 not_supported_arch() {
-  printf  "%${BUILD_INDENT}c $(print_color CLR_WARNING "*** ERROR: $PKG_ADDON_ID: '${DEVICE:-$PROJECT}' not supported ***")\n" ' '>&$SILENT_OUT
+  printf  "%${BUILD_INDENT}c $(print_color CLR_WARNING "*** SKIP: $PKG_ADDON_ID: '${DEVICE:-$PROJECT}' not supported ***")\n" ' '>&$SILENT_OUT
   exit 0
 }
 
 not_supported_device() {
-  printf  "%${BUILD_INDENT}c $(print_color CLR_WARNING "*** ERROR: $PKG_ADDON_ID: '$TARGET_ARCH' not supported ***")\n" ' '>&$SILENT_OUT
+  printf  "%${BUILD_INDENT}c $(print_color CLR_WARNING "*** SKIP: $PKG_ADDON_ID: '$TARGET_ARCH' not supported ***")\n" ' '>&$SILENT_OUT
   exit 0
 }
 
@@ -226,7 +228,7 @@ build_addon() {
 }
 
 # need parameter
-if [ $# == 0 ]; then
+if [ $# -eq 0 ]; then
   usage 1
 fi
 
@@ -236,6 +238,7 @@ addons_drop=""
 show_only="false"
 write_logs="no"
 log_path="$BUILD/logs"
+summary_file="/dev/null"
 export BUILD_INDENT=$((${BUILD_INDENT:-1}+$BUILD_INDENT_SIZE))
 
 # read addons from parameter list
@@ -262,6 +265,8 @@ case "$write_logs" in
 esac
 if [ -n "$log_path" ]; then
   mkdir -p "$log_path"
+  summary_file="$log_path/addon-summary.log"  
+  rm -f $summary_file
 fi
 
 # check environment and create toolchain
@@ -280,7 +285,7 @@ for addon in $(tr " " "\n" <<< $addons | sort -u); do
   fi
 
   # show-only: print name and continue with next addon
-  if [ $show_only == "true" ]; then
+  if [ "$show_only" = "true" ]; then
     echo $addon
     continue
   fi
@@ -299,16 +304,17 @@ for addon in $(tr " " "\n" <<< $addons | sort -u); do
   if [ ${PIPESTATUS[0]} != 0 ]; then
     addons_failed+="$addon "
     printf "$(print_color CLR_ERROR "ADDON FAILED $addon")\n" ' '>&$SILENT_OUT
+    echo "failed: ${addon}" >> $summary_file
   else
-    printf "$(print_color CLR_INFO "ADDON SUCCESS $addon")\n" ' '>&$SILENT_OUT
-    if [ $remove_success_logs == "true" ]; then
+    if [ "$remove_success_logs" = "true" ]; then
       rm -f $log_file
     fi
+    echo "success: ${addon}" >> $summary_file
   fi
 done
 
 # show-only has no summary, can exit here
-if [ $show_only == "true" ]; then
+if [ "$show_only" = "true" ]; then
   exit 0
 fi
 
